//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FIT5032_assi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassArrangement
    {
        public int ClassID { get; set; }
        public Nullable<int> Available { get; set; }
        public int ActivityID { get; set; }
        public int StaffID { get; set; }
        public Nullable<int> Id { get; set; }
    
        public virtual Activity Activity { get; set; }
        public virtual Client Client { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
